M48
; DRILL file {KiCad 7.0.5-0} date 2023 August 28, Monday 20:49:07
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-28T20:49:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.3344Y-4.834
X5.3344Y-5.984
X5.9094Y-5.984
X6.3594Y-5.984
T0
M30
